name: Deploy to Static.app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Static.app
        uses: 48jg6bdmjs-dot/parlayos-main
        with:
          api-key: ${{ secrets.STATIC_APP }}
